### ISSUE TITLE
Miniconda Distribution

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/Introductory#1]
Hi @ocefpaf, 

Welcome to geohackweek. It's a weeklong workshop where participants learn different open source tools to work with geospatial data. I am a part of the team of instructor. One of my job is to teach people about Conda. Last year I used Miniconda2. This year, I am planning to use Miniconda3. I was wondering if Miniconda3 is now mature enough for people to use? Thanks.

**Comment by ocefpaf** [comment]
@lsetiawan `miniconda3` is not a different version of `miniconda`, it is only a bundle with `Python 3` instead of `Python 2`. If you are installing `miniconda` and then creating environments it should not make a difference b/c the proper python version will be created using the specification in the env file.

PS: I only download `miniconda3` by BTW.

**Comment by lsetiawan** [comment]
Thanks for that explanation. I will start using `miniconda3`. 😃
